representation:
    _target_: networks.fully_connected.FcRepresentation
    hidden_depth: 5
    latent_shape: [2, 100]
prediction:
    _target_: networks.fully_connected.FcPrediction
    hidden_depth: 10
dynamics:
    _target_: networks.fully_connected.FcDynamics
    hidden_depth: 10
scalar_support_size: 100
