representation:
    _target_: networks.fully_connected.FcRepresentationId
    #hidden_depth: 1
prediction:
    _target_: networks.fully_connected.FcPrediction
    hidden_depth: 1
dynamics:
    _target_: networks.fully_connected.FcDynamics
    hidden_depth: 2
latent_shape: [50]
belief_shape: [0]
scalar_support_size: 11
