repos:
  - repo: local
    hooks:
      - id: check_bib_sort
        name: Check hayagriva bibliography key sort order
        entry: ./check_bib_sort.py
        language: python
        files: "bibliography.yml"
        additional_dependencies: ["pyyaml"]
      - id: check_typst_compile
        name: Check if the document compiles without errors
        entry: typst compile main.typ
        language: system
        always_run: true
        pass_filenames: false


    
