repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--check", "--diff"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: black (python)
        args: ["--check", "--diff"]
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.3.5
    hooks:
    -   id: pycln
        name: pycln (python)
        args: ["--check", "--diff"]
