repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--check", "--diff"]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        name: black (python)
        args: ["--check", "--diff"]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        name: pycln (python)
        args: ["--check", "--diff", "--all"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        language: python
        language_version: python3.11
        name: mypy (python)
        args: ["--enable-incomplete-feature=Unpack"]
