repos:
  - repo: local
    hooks:
      - id: check_bib_sort
        name: Check hayagriva bibliography key sort order
        entry: ./check_bib_sort.py
        language: python
        types: [yaml]
        additional_dependencies: ["pyyaml"]


    
