[tool.black]
line-length = 90

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 90
length_sort = true
float_to_top = true

[tool.mypy]
python_executable = "venv/bin/python"
strict = true
pretty = true
