[tool.black]
line-length = 90

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 90
length_sort = true
float_to_top = true

[tool.mypy]
strict = true
pretty = true

[[tool.mypy.overrides]]
module = [
    "pyspiel",
]
ignore_missing_imports = true
