[tool.black]
line-length = 90

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 90
length_sort = true
float_to_top = true

[tool.mypy]
python_executable = "venv/bin/python"
strict = true
pretty = true

[tool.flake8]
max-line-length = 90
show-source = true
extend-ignore = ["E203", "E741", "TC003", "TC006"]
extend-select = ["TC1"]
per-file-ignores = [
    "config/schema.py:TC004",
]
