batch_game_size: 16
batch_num_games: 4
discount_factor: 0.99
n_step_return: 20
replay_buffer_size: 1_000
max_moves_per_game: 10_000
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 1e-5
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: 1
    value: 1
    reward: 1
    policy: 1
    player_type: 1
