batch_game_size: 16
batch_num_games: 64
discount_factor: 0.95
n_step_return: 20
replay_buffer_size: 500
max_steps_per_episode: 10_000
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 1e-5
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: 0
    value: 1
    reward: 5
    policy: 1
    player_type: 1
