batch_game_size: 3
batch_num_games: 128
discount_factor: 0.96
n_step_return: 100
replay_buffer_size: 5000
max_steps_per_episode: 10_000
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 1e-3
    dynamics: 1
    prediction: 0.5
    representation: 10
loss_weights:
    latent: 1e-4
    value: 0.3
    reward: 0.5
    policy: 2
    player_type: 0.6
