batch_game_size: 16
batch_num_games: 64
discount_factor: 0.95
n_step_return: 20
replay_buffer_size: 1_000
max_steps_per_episode: 10_000
optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
loss_weights:
    latent: 0.1
    absorbing: 0.1
    value: 2
    reward: 3
    policy: 1
    beliefs: 0
    player_type: 1
