batch_game_size: 16
batch_num_games: 4
discount_factor: 0.99
n_step_return: 20
replay_buffer_size: 1_000
max_steps_per_episode: 10_000
optimizer:
    _target_: torch.optim.Adam
    lr: 0.005
loss_weights:
    latent: 1
    value: 1
    reward: 1
    policy: 1
    beliefs: 0
    player_type: 1
