batch_size: 128
train_selfplay_ratio: 50
min_trajectory_length: 3
max_trajectory_length: ${.min_trajectory_length}
discount_factor: 1
n_step_horizon: ${.max_steps_per_game}
replay_buffer_size: 50_000
max_steps_per_game: 1000
latent_dist_pnorm: 1
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 5e-6
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: auto
    value: auto
    reward: auto
    policy: auto
    turn: auto
