batch_size: 512
train_selfplay_ratio: 30
unroll_length: 2
discount_factor: 1
n_step_horizon: ${.max_steps_per_game}
replay_buffer_size: 20_000
random_play_steps: 200_000
max_steps_per_game: 1000
latent_dist_pnorm: 1
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 2e-4
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: 1e-4
    value: 1
    reward: 1
    policy: 1
    turn: 1
