batch_size: 128
train_selfplay_ratio: 50
unroll_length: 7
discount_factor: 1
n_step_horizon: ${.max_steps_per_game}
replay_buffer_size: 30_000
max_steps_per_game: 1000
latent_dist_pnorm: 2
optimizer:
    _target_: torch.optim.Adam
    weight_decay: 1e-4
learning_rates:
    base: 1e-3
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: 0.2
    value: 0.1
    reward: 1
    policy: 5e-3
    turn: 5
