batch_size: 256
train_selfplay_ratio: 100
unroll_length: 1
discount_factor: 1
n_step_horizon: ${.max_steps_per_game}
replay_buffer_size: 4000
max_steps_per_game: 1000
latent_dist_pnorm: 2
optimizer:
    _target_: torch.optim.Adam
learning_rates:
    base: 2e-5
    dynamics: 1
    prediction: 1
    representation: 1
loss_weights:
    latent: 1
    value: 1
    reward: 1
    policy: 1
    turn: 1
