representation:
    _target_: networks.fully_connected.FcRepresentation
prediction:
    _target_: networks.fully_connected.FcPrediction
dynamics:
    _target_: networks.fully_connected.FcDynamics
initial_beliefs:
    size: [50]
    fill_value: 0.5
initial_latent_rep:
    size: [50]
    fill_value: 0.5
