representation:
    _target_: networks.fully_connected.FcRepresentation
prediction:
    _target_: networks.fully_connected.FcPrediction
dynamics:
    _target_: networks.fully_connected.FcDynamics
latent_shape: [50]
