representation:
    _target_: networks.fully_connected.FcRepresentation
    hidden_depth: 2
prediction:
    _target_: networks.fully_connected.FcPrediction
    hidden_depth: 2
    width: 50
dynamics:
    _target_: networks.fully_connected.FcDynamics
    hidden_depth: 2
    width: 100
beliefs_shape: [0]
latent_rep_shape: [50]
