representation:
    _target_: networks.fully_connected.FcRepresentation
    hidden_depth: 1
prediction:
    _target_: networks.fully_connected.FcPrediction
    hidden_depth: 1
dynamics:
    _target_: networks.fully_connected.FcDynamics
    hidden_depth: 2
initial_beliefs:
    size: [0]
    fill_value: 0.5
initial_latent_rep:
    size: [10]
    fill_value: 0.5
