node_action_fn:
    _target_: fn.action.DrawFromPolicyFn
    policy_fn:
        _target_: fn.policy.FromExpandedValues
        softmax_temp: 0.3
node_target_policy_fn:
    _target_: fn.policy.FromExpandedValues
    softmax_temp: 0.2
node_selection_score_fn: ${fn:fn.selection.sample_from_prior}
iterations_move_selection: 10
iterations_value_estimate: 5
