get_node_action: fn.muzero.visit_count_action
get_node_target_policy: fn.muzero.visit_count_target
get_node_selection_score: fn.muzero.ucb_score
iterations_move_selection: 200
iterations_value_estimate: 100

visit_count_action:
    softmax_temp_start: 0.1
    softmax_temp_end: 0.1
    num_moves_start: 0
    num_moves_end: 1

visit_count_target:
    softmax_temp: 0.2

muzero_ucb:
    prior_log_scale_base: 5
    prior_log_scale_init: 1.25
