get_node_action: fn.action.from_visit_count
get_node_target_policy: fn.policy.from_visit_count
get_node_selection_score: fn.selection.ucb_score
iterations_move_selection: 200
iterations_value_estimate: 100

fn:
    action:
        from_visit_count:
            softmax_temp_start: 0.1
            softmax_temp_end: 0.1
            move_num_start: 0
            move_num_end: 0

    policy:
        from_visit_count:
            softmax_temp: 0.2

    selection:
        ucb_score:
            prior_log_scale_base: 5
            prior_log_scale_init: 1.25
