node_action_fn:
    _target_: fn.action.DrawFromPolicyFn
    policy_fn: ${fn:fn.policy.from_visit_counts}
node_target_policy_fn:
    _target_: fn.policy.FromExpandedValues
node_selection_score_fn: ${fn:fn.selection.from_prior_deterministic}
iterations_move_selection: 200
iterations_value_estimate: 100
