get_node_action: config.default_functions.greedy_node_action
get_node_target_policy: config.default_functions.muzero_node_target_policy
get_node_selection_score: config.default_functions.muzero_node_ucb_selection_score
iterations_move_selection: 200
iterations_value_estimate: 100

# for muzeros UCB formula:
ucb_prior_log_scale_base: 10000
ucb_prior_log_scale_init: 1.25
